##################################################
# NANMA unbiased 1 us production template
##################################################

# Select the original A or B starting structure.
set stateName        A
set replica          1
file mkdir output
set outName          output/unbiased_state_${stateName}_replica_${replica}
set inputPath        .

timestep             0.5
numsteps             2000000000

structure            ${inputPath}/alad.psf
coordinates          ${inputPath}/${stateName}.pdb
temperature          300.0
seed                 101234

outputname           ${outName}
restartname          ${outName}.restart
dcdFile              ${outName}.dcd

outputenergies       2000
outputtiming         2000
outputpressure       2000
restartfreq          2000
XSTFreq              2000
dcdFreq              2000

margin               10.0
stepspercycle        20
paraTypeCharmm       on
parameters           ${inputPath}/par_all22_prot.prm
exclude              scaled1-4
1-4scaling           1.0
switching            on
switchdist           16.0
cutoff               18.0
pairlistdist         20.0

langevin             on
langevinDamping      10.0
langevinTemp         300.0

colvars              on
colvarsConfig        ${inputPath}/colvars.in

firsttimestep        0
run                  2000000000
