##################################################
# Tri-alanine unbiased 1 us production template
##################################################

# A/B structures are from the original 0.Data/TOP_files directory.
set stateName        A
set replica          1
file mkdir output
set outName          output/unbiased_state_${stateName}_replica_${replica}
set inputPath        .
coordinates          ${inputPath}/${stateName}.pdb

numsteps             2000000000

parmfile             ${inputPath}/trialanine.parm7
seed                 101234

amber                on
cutoff               9.0
pairlistdist         11.0
switching            off
exclude              scaled1-4
readexclusions       yes
1-4scaling           0.83333333
scnb                 2.0
zeromomentum         on
ljcorrection         off
watermodel           tip3
nonbondedFreq        1
fullElectFrequency   1
hgroupcutoff         2.8

temperature          300.0
binaryoutput         no
binaryrestart        yes
outputname           ${outName}
restartname          ${outName}.restart
dcdFile              ${outName}.dcd

outputenergies       100000
outputtiming         100000
outputpressure       100000
restartfreq          100000
XSTFreq              0
dcdFreq              100

langevin             on
langevintemp         300.0
langevindamping      1.0

timestep             0.5
rigidbonds           none
stepspercycle        16
splitpatch           hydrogen
margin               2.0

colvars              on
colvarsConfig        colvars.in
